apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: db-backup
  namespace: backup
spec:
  schedule: "12 */3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: job
            image: rg.fr-par.scw.cloud/iben12/db-backup-job:latest
            args: ['backup']
            env:
              - name: SERVICE_ACCOUNT_PATH
                value: "/var/run/secrets/svc_account.json"
            envFrom:
            - secretRef:
                name: backup-secrets
            volumeMounts:
            - name: secrets
              mountPath: "/var/run/secrets"
              readOnly: true
          volumes:
          - name: secrets
            secret:
              secretName: gcp-svc-account
          restartPolicy: OnFailure
          imagePullSecrets:
          - name:  scw-registry
  concurrencyPolicy: Forbid