name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: false

    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v2.x

    - uses: docker/build-push-action@v1
      name: Build and push
      env:
        DOCKER_BUILDKIT: 1
      with:
        username: nologin
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: db-backup-job
        registry: rg.fr-par.scw.cloud/iben12
        tags: latest, ${{ env.GITHUB_SHA_SHORT }}

    - name: Show image
      run: |
        echo "sha: ${{ env.GITHUB_SHA_SHORT }} image: rg.fr-par.scw.cloud/iben12/db-backup-job:${{ env.GITHUB_SHA_SHORT }}"

    - name: deploy to staging
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
      with:
        args: set image cronjob/db-backup job=rg.fr-par.scw.cloud/iben12/db-backup-job:${{ env.GITHUB_SHA_SHORT }} -n backup
